Q = chr(39)
T = chr(9)
TT = chr(9)*2
TTT = chr(9)*3
TTTT = chr(9)*4
L = []
def a(*args):
    for x in args: L.append(x)
def q(s): return Q+s+Q
OUT = 'D:/Documents/Workspace/MokoDoliTraining/src/class/MokoDoliTrainingSeed.class.php'
import base64
L.append(base64.b64decode('PD9waHAKLyoKICogQ29weXJpZ2h0IChDKSAyMDI2IE1va28gQ29uc3VsdGluZyA8aGVsbG9AbW9rb2NvbnN1bHRpbmcudGVjaD4KICogVGhpcyBmaWxlIGlzIHBhcnQgb2YgYSBNb2tvIENvbnN1bHRpbmcgcHJvamVjdC4KICogU1BEWC1MaWNlbnNlLUlkZW50aWZpZXI6IEdQTC0zLjAtb3ItbGF0ZXIKICoKICogREVGR1JPVVA6IE1va29Eb2xpVHJhaW5pbmcuU2VlZAogKiBJTkdST1VQOiAgTW9rb0RvbGlUcmFpbmluZwogKiBSRVBPOiAgICAgaHR0cHM6Ly9naXRodWIuY29tL21va29jb25zdWx0aW5nLXRlY2gvTW9rb0RvbGlUcmFpbmluZwogKiBQQVRIOiAgICAgL3NyYy9jbGFzcy9Nb2tvRG9saVRyYWluaW5nU2VlZC5jbGFzcy5waHAKICogVkVSU0lPTjogIGRldmVsb3BtZW50CiAqIEJSSUVGOiAgICBUcmFpbmluZyBkYXRhIHNlZWRlcjogaW5zZXJ0cyB0cmFpbmluZyByb3dzLCB0cmFja3MgSURzIGluCiAqICAgICAgICAgICBsbHhfbW9rb2RvbGl0cmFpbmluZ19tYW5pZmVzdCwgYW5kIHByb3ZpZGVzIHByb2dyYW1tYXRpYyByZXNldC4KICoKICogTk9URTogQWxsIHNlZWQgZGF0YSBpcyBpbmplY3RlZCBwcm9ncmFtbWF0aWNhbGx5IHZpYSBzZWVkU3RhdGljKCkgYW5kIHNlZWRPcmRlcnMoKS4KICogICAgICAgTm8gU1FMIGZpbGVzIGFyZSB1c2VkIGZvciBzZWVkaW5nLgogKi8KCmNsYXNzIE1va29Eb2xpVHJhaW5pbmdTZWVkCnsKCXByaXZhdGUgJGRiOwo=').decode())
